### ISSUE TITLE
Improve & optimize gossipsub

### ISSUE THREAD

**Issue by Menduist** [vacp2p/nim-libp2p#633]
Epic issue to follow the various improvements for gossipsub

- [x] Don't relay message to the peer who sent it to us (#625)
- [x] Validate pubsub subscriptions (#627)
- [x] Don't relay to any peer that has seen message already (#626)
- [ ] Find a better way to do metrics
  - It's really clunky ATM. A better solution could be to give endpoint to programs to set whatever metrics they want.
- [ ] Control message piggy-backing? Would only save bandwidth in some specific scenarios
